name: Test
on: [push]
jobs:
  on_build_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run:
          cd $GITHUB_WORKSPACE
          yarn add --dev jest
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
      - name: Run Tests
        run: yarn test
